name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  install-podman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Podman
        uses: gacts/install-podman@v1
        
      - name: Run test script
        run: |
          chmod +x ./test.sh
          ./test.sh
  